development:
    database: contentator_dev 
    adapter: mysql 
    hostname: localhost 
    username: root 
    password: cr41g

test:
    database: contentator_test
    adapter: mysql
    hostname: localhost
    username: root
    password: cr41g

production:
    database: contentator_prod
    adapter: mysql
    hostname: localhost
    username: root
    password: cr41g
