gems:
- name: thoughtbot-shoulda
  version: '>= 2.10.2'
  lib: 'shoulda'
  source: 'http://gems.github.com'
- name: thoughtbot-factory_girl
  version: '>= 1.2.2'
  lib: 'factory_girl'
  source: 'http://gems.github.com'
- name: haml
  version: '>= 2.2.6' 
  